### ISSUE TITLE
Add acceptance field to a user.

### ISSUE THREAD

**Issue by oggnik** [oggnik/acm-hscc#19]
In case we have a ton of people sign up, we may want to not fully accept people immediately.

Afterwords we can accept a bunch of people and send emails saying they got in.

**Comment by gorel** [comment]
Easier solution: Just add a disclaimer that there's no guarantee they will get in and this is just the application process.

**Comment by oggnik** [comment]
We will email them if they get in, right?

**Comment by gorel** [comment]
Yeah. Most likely, we will email their teachers.

**Comment by oggnik** [comment]
Should we get their teachers contact info then also?  Or is that assumed since we are inviting the schools?

**Comment by gorel** [comment]
It's assumed. We'll only send this link out to certain schools.

Others could potentially register, but we just won't accept them.. lol

**Comment by oggnik** [comment]
:+1:
