### ISSUE TITLE
To make the site work with the Apache pass we need a few changes I think

### ISSUE THREAD

**Issue by vidia** [oggnik/acm-hscc#51]
Can you make the links to images and stylesheets use the full url "acm.cs.purdue.edu/hscc/" or "/hscc/"? Right now that page forwards properly, but it doesn't load images and CSS correctly right now. I am not sure if I can make it forward completely correctly or not without that change.

**Comment by oggnik** [comment]
Do I also need to add /hscc/ to the other calls? For example the login post call?

**Comment by oggnik** [comment]
Yeah, looks like I do.  I'll add an environmental variable to prepend to all the URLs

**Comment by oggnik** [comment]
@oggnik For future reference: app.config["APPLICATION_ROOT"] = "/abc/123"

**Comment by oggnik** [comment]
@vidia The entire site is now running on /hscc, can you update the apache settings to match it? (Instead of pointing to "IP", point it to "IP/hscc")
Thanks

**Comment by oggnik** [comment]
Works now, thanks @vidia
